name: User Service API Automation

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  pull:
    name: Pulling from repo
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
  install_and_build:
    runs-on: self-hosted
    name: Install deps and build
    needs: pull
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - name: Install dependencies
        run: yarn install
      - name: Update prisma dependencies
        run: npx prisma generate
      - name: Build
        run: yarn build
  upload_container:
    runs-on: self-hosted
    name: Update Container
    needs: install_and_build
    steps:
      - name: Stop Container
        working-directory: .docker
        run: docker compose down -v
      - name: Start Container
        working-directory: .docker
        run: docker compose up -d --force-recreate --renew-anon-volumes
