name: User Service API Automation

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  pull:
    name: Pulling from repo
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
  run_container:
    runs-on: self-hosted
    name: Update Container
    needs: install_and_build
    steps:
      - name: Stop Container
        run: docker compose down -v
      - name: Start Container
        run: docker compose up -d --force-recreate --renew-anon-volumes
